# -*- coding: utf-8 -*-
"""Azizah Qonita Hisanah Yefri_F0403251046_Post Test 4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LJEol_TOkCii__go7csE3mmZwoVjl3lG
"""

# ==========================================================
# SISTEM PENJUALAN KOPI NANGGUNG
# Mata Kuliah : Algoritma Pemrograman
# Studi Kasus : Penjualan Produk Kopi
# ==========================================================
from datetime import datetime
# -----------------------------
# Fungsi Judul
# -----------------------------
def garis():
  print("=" * 65)
def garis2():
  print("-" * 65)

garis()
print(" KOPERASI KOPI NANGGUNG AMANAT")
print(" Sistem Penjualan Produk Kopi Nusantara")
garis()

# -----------------------------
# Tanggal Transaksi
# -----------------------------
tanggal = datetime.now().strftime("%d %B %Y")
jam = datetime.now().strftime("%H:%M:%S")

print(f"Tanggal Transaksi : {tanggal}")
print(f"Jam Transaksi : {jam}")

garis()

# -----------------------------
# Input Pembeli
# -----------------------------
nama = input("Nama Pembeli : ")

print("\nDAFTAR PRODUK KOPI")
garis2()
print("Kode Produk Harga/kg")
garis2()
print("GBR Green Bean Robusta Rp 45.000")
print("RBR Roasted Bean Robusta Rp 85.000")
print("ARB Arabica Premium Rp120.000")
print("ESP Espresso Blend Rp140.000")
print("DRP Drip Bag Coffee Rp165.000")
garis2()

kode = input("Masukkan kode produk : ").upper()
berat = float(input("Masukkan jumlah (kg) : "))

# -----------------------------
# Menentukan Produk
# -----------------------------

if kode == "GBR":
    produk = "Green Bean Robusta"
    harga = 45000
elif kode == "RBR":
    produk = "Roasted Bean Robusta"
    harga = 85000
elif kode == "ARB":
    produk = "Arabica Premium"
    harga = 120000
elif kode == "ESP":
    produk = "Espresso Blend"
    harga = 140000
elif kode == "DRP":
    produk = "Drip Bag Coffee"
    harga = 165000
else:
    print("\nKode produk tidak tersedia.")
    exit()

# -----------------------------
# Perhitungan
# -----------------------------

subtotal = harga * berat
# Diskon
if subtotal >= 1000000:
    diskon = subtotal * 0.10
elif subtotal >= 500000:
    diskon = subtotal * 0.05
else:
    diskon = 0

# Setelah diskon
setelah_diskon = subtotal - diskon

# Pajak
ppn = setelah_diskon * 0.11

# -----------------------------
# Ongkir
# -----------------------------
print("\nKOTA TUJUAN")
print("1. Bogor")
print("2. Jakarta")
print("3. Bandung")
print("4. Luar Jawa")

kota_input = input("Pilih kota (contoh: Bogor, Jakarta, Bandung, Luar Jawa) : ").lower()

if kota_input == "bogor":
    nama_kota = "Bogor"
    ongkir = 15000

elif kota_input == "jakarta":
    nama_kota = "Jakarta"
    ongkir = 25000

elif kota_input == "bandung":
    nama_kota = "Bandung"
    ongkir = 30000

elif kota_input == "luar jawa":
    nama_kota = "Luar Jawa"
    ongkir = 60000

else:
    print("Pilihan kota tidak tersedia.")
    exit()

# -----------------------------
# Bonus
# -----------------------------
if berat >= 20:
    bonus = "Tumbler Exclusive"

elif berat >= 10:
    bonus = "Mug Kopi"

elif berat >= 5:
    bonus = "Sticker Kopi"

else:
    bonus = "-"

# -----------------------------
# Total Bayar
# -----------------------------
total = setelah_diskon + ppn + ongkir

# -----------------------------
# Pembayaran
# -----------------------------
print("\nMetode Pembayaran")
print("1. Tunai")
print("2. QRIS")
print("3. Transfer Bank")

metode_input = input("Pilih metode (contoh: Tunai, QRIS, Transfer Bank) : ").lower()

if metode_input == "tunai":
    pembayaran = "Tunai"

elif metode_input == "qris":
    pembayaran = "QRIS"

elif metode_input == "transfer bank":
    pembayaran = "Transfer Bank"

else:
    print("Metode tidak tersedia.")
    exit()

print()

bayar = float(input("Masukkan nominal pembayaran : Rp "))

kembalian = bayar - total
# -----------------------------
# Status Pembayaran
# -----------------------------
if bayar >= total:
    status = "LUNAS"
else:
    status = "PEMBAYARAN KURANG"

# -----------------------------
# Cetak Struk
# -----------------------------

print("\n")
garis()
print("                   STRUK PENJUALAN")
garis()

print(f"Nama Pembeli      :  {nama}")
print(f"Tanggal           : {tanggal}")
print(f"Jam               : {jam}")

garis2()

print(f"Produk            : {produk}")
print(f"Kode Produk       : {kode}")
print(f"Berat             : {berat:.2f} kg")
print(f"Harga/kg          : Rp {harga:,.0f}")

garis2()

print(f"Subtotal        : Rp {subtotal:,.0f}")
print(f"Diskon          : Rp {diskon:,.0f}")
print(f"PPN (11%)       : Rp {ppn:,.0f}")
print(f"Ongkos Kirim    : Rp {ongkir:,.0f}")

garis2()

print(f"TOTAL BAYAR       : Rp {total:,.0f}")
print(f"Pembayaran        : {pembayaran}")
print(f"Uang Dibayar      : Rp {bayar:,.0f}")

if bayar >= total:
    print(f"Kembalian : Rp {kembalian:,.0f}")
else:
    print(f"Kekurangan : Rp {abs(kembalian):,.0f}")

print(f"Status            : {status}")
print(f"Bonus             : {bonus}")
print(f"Kota Tujuan       : {nama_kota}")

garis()
print(" Terima kasih telah berbelanja di")
print(" KOPERASI KOPI NANGGUNG AMANAT")
print(" Mendukung Kopi Lokal Indonesia")
garis()

print("Halo, Google Colab!")